/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author john mark
 */
public class Home extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        setLayout(new java.awt.BorderLayout());
        setPanel(dash);
        MainPanel.setLayout(new java.awt.BorderLayout());
        MainPanel.removeAll();
        MainPanel.add(dash, java.awt.BorderLayout.CENTER);
        MainPanel.revalidate();
        MainPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        generateReport = new javax.swing.JLabel();
        studReg = new javax.swing.JLabel();
        CourseEnroll = new javax.swing.JLabel();
        gradeMan = new javax.swing.JLabel();
        dashBoard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 940));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 940));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 45)); // NOI18N
        jLabel3.setText("Jose Rizal University");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 730, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("LOGO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, -1));

        jLabel2.setText("Rizal, Philippines");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 20));

        generateReport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        generateReport.setText("Generate Report");
        getContentPane().add(generateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, -1, -1));

        studReg.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        studReg.setText("Student Registration");
        studReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studRegMouseClicked(evt);
            }
        });
        getContentPane().add(studReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        CourseEnroll.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CourseEnroll.setText("Course Enrollment");
        getContentPane().add(CourseEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        gradeMan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        gradeMan.setText("Grade Management");
        gradeMan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeManMouseClicked(evt);
            }
        });
        getContentPane().add(gradeMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));

        dashBoard.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dashBoard.setText("Dashboard");
        dashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashBoardMouseClicked(evt);
            }
        });
        getContentPane().add(dashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel1.setText("________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1920, -1));

        MainPanel.setBackground(new java.awt.Color(242, 242, 255));
        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1245, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DashBoard dash = new DashBoard();
    //StudentRegistration studReg = new StudentRegistration();
    GradeManagement gradeManage = new GradeManagement();
    
    public void setPanel(javax.swing.JPanel panel) {
    MainPanel.removeAll();
    MainPanel.add(panel, java.awt.BorderLayout.CENTER);
    MainPanel.revalidate();
    MainPanel.repaint();
}

    private void dashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashBoardMouseClicked
        MainPanel.removeAll();
        MainPanel.add(dash, java.awt.BorderLayout.CENTER);
        MainPanel.revalidate();
        MainPanel.repaint();

    }//GEN-LAST:event_dashBoardMouseClicked

    private void studRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studRegMouseClicked
        MainPanel.removeAll();
        setPanel(new StudentRegistration(this));
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_studRegMouseClicked

    private void gradeManMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeManMouseClicked
        MainPanel.removeAll();
        MainPanel.add(gradeManage, java.awt.BorderLayout.CENTER);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_gradeManMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CourseEnroll;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel dashBoard;
    private javax.swing.JLabel generateReport;
    private javax.swing.JLabel gradeMan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel studReg;
    // End of variables declaration//GEN-END:variables

}
