/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Spooky
 */
public class StudentRegistrationRequiredDocu extends javax.swing.JPanel {

    /**
     * Creates new form StudentRegistration
     */
    Home parent;
    
    public StudentRegistrationRequiredDocu(Home parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fileUploader1 = new FileUploader();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fileUploader2 = new FileUploader();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fileUploader3 = new FileUploader();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fileUploader4 = new FileUploader();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fileUploader5 = new FileUploader();
        jLabel15 = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1280, 770));
        setPreferredSize(new java.awt.Dimension(1245, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 610, 172, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Document");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Upload");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Birth Certificate(PSA)");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        javax.swing.GroupLayout fileUploader1Layout = new javax.swing.GroupLayout(fileUploader1);
        fileUploader1.setLayout(fileUploader1Layout);
        fileUploader1Layout.setHorizontalGroup(
            fileUploader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        fileUploader1Layout.setVerticalGroup(
            fileUploader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        add(fileUploader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, 54));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Status");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Pending");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Pending");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 320, -1, -1));

        javax.swing.GroupLayout fileUploader2Layout = new javax.swing.GroupLayout(fileUploader2);
        fileUploader2.setLayout(fileUploader2Layout);
        fileUploader2Layout.setHorizontalGroup(
            fileUploader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        fileUploader2Layout.setVerticalGroup(
            fileUploader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        add(fileUploader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, 54));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Form 137/ Form 138");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Pending");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 380, -1, -1));

        javax.swing.GroupLayout fileUploader3Layout = new javax.swing.GroupLayout(fileUploader3);
        fileUploader3.setLayout(fileUploader3Layout);
        fileUploader3Layout.setHorizontalGroup(
            fileUploader3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        fileUploader3Layout.setVerticalGroup(
            fileUploader3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        add(fileUploader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, 54));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Good Moral Certificate");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Pending");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 440, -1, -1));

        javax.swing.GroupLayout fileUploader4Layout = new javax.swing.GroupLayout(fileUploader4);
        fileUploader4.setLayout(fileUploader4Layout);
        fileUploader4Layout.setHorizontalGroup(
            fileUploader4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        fileUploader4Layout.setVerticalGroup(
            fileUploader4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        add(fileUploader4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, 54));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("2x2 ID Picture ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Pending");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 500, -1, -1));

        javax.swing.GroupLayout fileUploader5Layout = new javax.swing.GroupLayout(fileUploader5);
        fileUploader5.setLayout(fileUploader5Layout);
        fileUploader5Layout.setHorizontalGroup(
            fileUploader5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        fileUploader5Layout.setVerticalGroup(
            fileUploader5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        add(fileUploader5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, -1, 54));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Certificate of Graduation");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        nextBtn.setText("Next");
        nextBtn.addActionListener(this::nextBtnActionPerformed);
        add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, 172, 67));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Student Registration");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
         parent.setPanel(new StudentRegistration(parent));
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private FileUploader fileUploader1;
    private FileUploader fileUploader2;
    private FileUploader fileUploader3;
    private FileUploader fileUploader4;
    private FileUploader fileUploader5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton nextBtn;
    // End of variables declaration//GEN-END:variables
}
