/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Spooky
 */
public class StudentRegistration extends javax.swing.JPanel {

    /**
     * Creates new form StudentRegistration
     */
    Home parent;
    
    public StudentRegistration(Home parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        firstName2 = new javax.swing.JTextField();
        firstName1 = new javax.swing.JTextField();
        datePicker1 = new DatePicker();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        firstName3 = new javax.swing.JTextField();
        firstName4 = new javax.swing.JTextField();
        nxtBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1245, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Student Registration");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jTextField1.setText("Surname");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 45));

        firstName.setText("First Name");
        firstName.addActionListener(this::firstNameActionPerformed);
        add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, 45));

        firstName2.setText("Middle Name");
        firstName2.addActionListener(this::firstName2ActionPerformed);
        add(firstName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 170, 45));

        firstName1.setText("Suffix");
        firstName1.addActionListener(this::firstName1ActionPerformed);
        add(firstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 108, 45));
        add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 45));

        jRadioButton2.setText("Female");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jTextField3.setText("Nationality");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 40));

        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jTextField2.setText("Address");
        jTextField2.setPreferredSize(new java.awt.Dimension(64, 45));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 541, 40));

        jTextField4.setText("Previous School Attended");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 550, 45));

        firstName3.setText("Chosen Course/Program");
        firstName3.addActionListener(this::firstName3ActionPerformed);
        add(firstName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 350, 45));

        firstName4.setText("Last Year Level Completed");
        firstName4.addActionListener(this::firstName4ActionPerformed);
        add(firstName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 179, 45));

        nxtBtn.setText("Next");
        nxtBtn.addActionListener(this::nxtBtnActionPerformed);
        add(nxtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 630, 172, 67));
    }// </editor-fold>//GEN-END:initComponents

    private void firstName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName4ActionPerformed

    private void firstName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void firstName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName1ActionPerformed

    private void firstName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName2ActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void nxtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtBtnActionPerformed
        parent.setPanel(new StudentRegistrationRequiredDocu(parent));
    }//GEN-LAST:event_nxtBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DatePicker datePicker1;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField firstName1;
    private javax.swing.JTextField firstName2;
    private javax.swing.JTextField firstName3;
    private javax.swing.JTextField firstName4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton nxtBtn;
    // End of variables declaration//GEN-END:variables
}
